# Test commit on all supported platforms and Python versions.
name: Test commit

on: [push, pull_request, workflow_dispatch]

jobs:

  # Test on all three platforms.
  platform:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code.
        uses: actions/checkout@v5

      - name: Set up Python.
        uses: actions/setup-python@v6
        with:
            python-version: 3.x

      - name: Install project.
        run:  pip install .[dev]

      - name: Run tests.
        run:  pytest


  # Test on all supported Python versions.
  Python:

    strategy:
        matrix:
            python: ['3.9', '3.10', '3.11', '3.12', '3.13']

    runs-on: ubuntu-latest

    steps:
      - name: Check out code.
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python }}.
        uses: actions/setup-python@v6
        with:
            python-version: ${{ matrix.python }}
            allow-prereleases: true

      - name: Install package.
        run:  pip install .[dev]

      - name: Run tests.
        run:  pytest
