# Test commit on all supported platforms and Python versions.
name: Test commit

on: [push, pull_request, workflow_dispatch]

jobs:

  # Test on all three platforms.
  platform:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code.
        uses: actions/checkout@v3

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - name: Install project.
        run:  pip install .[dev]

      - name: Run tests.
        run:  pytest


  # Test on all supported Python versions.
  Python:

    strategy:
        matrix:
            python: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']

    runs-on: ubuntu-latest

    steps:
      - name: Check out code.
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}.
        uses: actions/setup-python@v4
        with:
            python-version: ${{ matrix.python }}

      - name: Install package.
        run:  pip install .[dev]

      - name: Run tests.
        run:  pytest
